/// End-to-end validation: compare generated CSV structure against
/// real factory files from Prin's factory, Si Racha, Thailand.
///
/// These tests don't assert byte-for-byte equality — the real files
/// are generated by FrameBuilderMRD from a specific building design
/// we don't have. Instead they validate that:
///   1. Our generated CSV parses correctly
///   2. Key structural properties match (component count, operation types,
///      label pairing, length ranges, dimple pair spacing)
///   3. The roundtrip is lossless

use howick_rs::csv;
use howick_rs::types::{LabelOrientation, Operation, Unit};

// ── Real factory fixtures ─────────────────────────────────────────────────────

const T1_REAL: &str = include_str!("fixtures/T1_full.csv");
const W1_REAL: &str = include_str!("fixtures/W1_full.csv");

// ── Simulated generated output ────────────────────────────────────────────────
// These mirror what the howick WASM plugin produces for a simple wall panel
// matching W1's approximate dimensions: 4740mm long, 2400mm high, 600mm spacing.

fn make_simple_wall() -> howick_rs::types::Frameset {
    use howick_rs::types::*;

    // Approximate W1: 4740mm long wall, 600mm stud spacing
    // Top + bottom tracks (U section, 4740mm)
    // Studs at 0, 600, 1200, 1800, 2400, 3000, 3600, 4200, 4740mm = 9 positions
    // Each stud: 2400mm high C-section

    let wall_length  = 4740.0_f64;
    let wall_height  = 2400.0_f64;
    let spacing      = 600.0_f64;
    let dimple_near  = 20.65_f64;
    let dimple_gap   = 50.0_f64;

    let mut components = Vec::new();
    let mut comp_idx = 1usize;

    // Tracks (top and bottom) — INV/NRM pair each
    for _track in 0..2 {
        let mut ops = Vec::new();
        let mut pos = spacing;
        while pos < wall_length - 20.0 {
            ops.push(Operation::Dimple(pos));
            ops.push(Operation::Dimple(pos + dimple_gap));
            pos += spacing;
        }
        ops.push(Operation::LipCut(23.0));
        ops.push(Operation::LipCut(wall_length - 23.0));

        for label in [LabelOrientation::Inverted, LabelOrientation::Normal] {
            components.push(Component {
                id: format!("W1-{}", comp_idx),
                label,
                quantity: 1,
                length_mm: wall_length,
                operations: ops.clone(),
            });
            comp_idx += 1;
        }
    }

    // Studs — C-section, 2400mm high, INV/NRM pairs
    let mut x = 0.0_f64;
    while x <= wall_length + 1.0 {
        let ops = vec![
            Operation::Dimple(dimple_near),
            Operation::Dimple(dimple_near + dimple_gap),
            Operation::Dimple(wall_height - dimple_near - dimple_gap),
            Operation::Dimple(wall_height - dimple_near),
            Operation::LipCut(23.0),
            Operation::LipCut(wall_height - 23.0),
            Operation::ServiceHole(wall_height / 2.0),
        ];
        for label in [LabelOrientation::Inverted, LabelOrientation::Normal] {
            components.push(Component {
                id: format!("W1-{}", comp_idx),
                label,
                quantity: 1,
                length_mm: wall_height,
                operations: ops.clone(),
            });
            comp_idx += 1;
        }
        if (x - wall_length).abs() < 1.0 { break; }
        x = (x + spacing).min(wall_length);
    }

    Frameset {
        name: "W1".into(),
        unit: Unit::Millimetre,
        profile: howick_rs::types::Profile {
            code: "S8908".into(),
            description: "Standard Profile".into(),
        },
        components,
    }
}

// ── Structural property helpers ───────────────────────────────────────────────

fn count_op(frameset: &howick_rs::types::Frameset, pred: fn(&Operation) -> bool) -> usize {
    frameset.components.iter()
        .flat_map(|c| c.operations.iter())
        .filter(|op| pred(op))
        .count()
}

fn label_counts(frameset: &howick_rs::types::Frameset) -> (usize, usize) {
    let inv = frameset.components.iter().filter(|c| c.label == LabelOrientation::Inverted).count();
    let nrm = frameset.components.iter().filter(|c| c.label == LabelOrientation::Normal).count();
    (inv, nrm)
}

fn dimple_spacings(frameset: &howick_rs::types::Frameset) -> Vec<f64> {
    // For each component, find consecutive dimple positions and compute spacings
    frameset.components.iter().flat_map(|c| {
        let mut dimples: Vec<f64> = c.operations.iter()
            .filter_map(|op| if let Operation::Dimple(p) = op { Some(*p) } else { None })
            .collect();
        dimples.sort_by(|a, b| a.partial_cmp(b).unwrap());
        dimples.windows(2).map(|w| (w[1] - w[0]).abs()).collect::<Vec<_>>()
    }).collect()
}

// ── Tests against real T1 truss ───────────────────────────────────────────────

#[test]
fn t1_real_has_label_symmetry() {
    let f = csv::parse(T1_REAL).unwrap();
    let (inv, nrm) = label_counts(&f);
    assert_eq!(inv, nrm, "T1 real: INV/NRM must be equal, got {inv} INV {nrm} NRM");
}

#[test]
fn t1_real_dimple_pairs_are_50mm() {
    let f = csv::parse(T1_REAL).unwrap();
    // In the truss, dimples come in pairs ~50mm apart at each connection point.
    // Between pairs the spacing is ~383mm. So roughly 1 in every 4 spacings is ~50mm.
    let spacings = dimple_spacings(&f);
    let near_50 = spacings.iter().filter(|&&s| (s - 50.0).abs() < 2.0).count();
    let total = spacings.len();
    // At least 25% of spacings should be the 50mm pair gap
    assert!(
        near_50 * 4 >= total,
        "T1 real: expected ≥25% ~50mm dimple spacings, got {near_50}/{total}"
    );
}

#[test]
fn t1_real_all_operations_parse() {
    let f = csv::parse(T1_REAL).unwrap();
    assert!(count_op(&f, |op| matches!(op, Operation::Dimple(_))) > 0);
    assert!(count_op(&f, |op| matches!(op, Operation::LipCut(_))) > 0);
    assert!(count_op(&f, |op| matches!(op, Operation::Swage(_))) > 0);
    assert!(count_op(&f, |op| matches!(op, Operation::Web(_))) > 0);
    assert!(count_op(&f, |op| matches!(op, Operation::EndTruss(_))) > 0);
}

#[test]
fn t1_real_chord_members_are_longest() {
    let f = csv::parse(T1_REAL).unwrap();
    let max_len = f.components.iter().map(|c| c.length_mm as u64).max().unwrap();
    // T1-1 and T1-2 are 3945mm — the chord members
    assert_eq!(max_len, 3945);
}

// ── Tests against real W1 wall ────────────────────────────────────────────────

#[test]
fn w1_real_has_notch_and_service_hole() {
    let f = csv::parse(W1_REAL).unwrap();
    assert!(count_op(&f, |op| matches!(op, Operation::Notch(_))) > 0,
        "W1 real: must have NOTCH operations (door/window openings)");
    assert!(count_op(&f, |op| matches!(op, Operation::ServiceHole(_))) > 0,
        "W1 real: must have SERVICE_HOLE operations");
}

#[test]
fn w1_real_tracks_are_longest() {
    let f = csv::parse(W1_REAL).unwrap();
    let max_len = f.components.iter().map(|c| c.length_mm as u64).max().unwrap();
    // W1-1 and W1-2 are 4740mm — the top/bottom tracks
    assert_eq!(max_len, 4740);
}

#[test]
fn w1_real_unit_is_millimetre() {
    let f = csv::parse(W1_REAL).unwrap();
    assert_eq!(f.unit, Unit::Millimetre);
}

#[test]
fn w1_real_profile_is_s8908() {
    let f = csv::parse(W1_REAL).unwrap();
    assert_eq!(f.profile.code, "S8908");
}

// ── Tests against generated W1 ────────────────────────────────────────────────

#[test]
fn generated_w1_parses_cleanly() {
    let frameset = make_simple_wall();
    let csv_str  = csv::serialize(&frameset).unwrap();
    let parsed   = csv::parse(&csv_str).unwrap();
    assert_eq!(parsed.name, "W1");
    assert_eq!(parsed.unit, Unit::Millimetre);
    assert_eq!(parsed.profile.code, "S8908");
}

#[test]
fn generated_w1_has_label_symmetry() {
    let frameset = make_simple_wall();
    let (inv, nrm) = label_counts(&frameset);
    assert_eq!(inv, nrm,
        "Generated W1: INV/NRM must be equal, got {inv} INV {nrm} NRM");
}

#[test]
fn generated_w1_dimple_pairs_are_50mm() {
    let frameset = make_simple_wall();
    let spacings = dimple_spacings(&frameset);
    let near_50  = spacings.iter().filter(|&&s| (s - 50.0).abs() < 1.0).count();
    assert!(near_50 > 0,
        "Generated W1: must have ~50mm dimple pair spacings");
}

#[test]
fn generated_w1_has_tracks_at_wall_length() {
    let frameset  = make_simple_wall();
    let max_len   = frameset.components.iter().map(|c| c.length_mm as u64).max().unwrap();
    assert_eq!(max_len, 4740, "Track length must match wall length");
}

#[test]
fn generated_w1_studs_are_2400mm() {
    let frameset = make_simple_wall();
    let stud_count = frameset.components.iter()
        .filter(|c| (c.length_mm - 2400.0).abs() < 1.0)
        .count();
    assert!(stud_count > 0, "Must have 2400mm stud members");
}

#[test]
fn generated_w1_roundtrip_lossless() {
    let original  = make_simple_wall();
    let csv_str   = csv::serialize(&original).unwrap();
    let reparsed  = csv::parse(&csv_str).unwrap();

    assert_eq!(original.components.len(), reparsed.components.len());
    for (o, r) in original.components.iter().zip(reparsed.components.iter()) {
        assert_eq!(o.id,        r.id);
        assert_eq!(o.label,     r.label);
        assert_eq!(o.length_mm, r.length_mm);
        assert_eq!(o.operations.len(), r.operations.len(),
            "Component {}: operation count mismatch", o.id);
    }
}

#[test]
fn generated_w1_has_service_holes_at_mid_height() {
    let frameset = make_simple_wall();
    let service_holes: Vec<f64> = frameset.components.iter()
        .flat_map(|c| c.operations.iter())
        .filter_map(|op| if let Operation::ServiceHole(p) = op { Some(*p) } else { None })
        .collect();
    assert!(!service_holes.is_empty(), "Must have service holes");
    // All service holes should be at mid-height (1200mm for 2400mm studs)
    for pos in &service_holes {
        assert!((*pos - 1200.0).abs() < 1.0,
            "Service hole at {pos}mm, expected ~1200mm (mid stud height)");
    }
}

// ── Cross-validation: generated vs real structure ─────────────────────────────

#[test]
fn generated_w1_operation_types_subset_of_real() {
    // Generated W1 uses: DIMPLE, LIP_CUT, SERVICE_HOLE
    // Real W1 uses all 7 types (including NOTCH, SWAGE, WEB, END_TRUSS for complex members)
    // Generated should at minimum have the basic three
    let generated = make_simple_wall();
    assert!(count_op(&generated, |op| matches!(op, Operation::Dimple(_))) > 0);
    assert!(count_op(&generated, |op| matches!(op, Operation::LipCut(_))) > 0);
    assert!(count_op(&generated, |op| matches!(op, Operation::ServiceHole(_))) > 0);
}

#[test]
fn real_w1_operation_types_superset_of_generated() {
    // The real file has richer operation types — confirms our generated
    // output is conservative (correct for simple walls, real file has trusses too)
    let real = csv::parse(W1_REAL).unwrap();
    assert!(count_op(&real, |op| matches!(op, Operation::Notch(_))) > 0,
        "Real W1 must have NOTCH (door/window openings) — our generator doesn't yet");
    assert!(count_op(&real, |op| matches!(op, Operation::Swage(_))) > 0,
        "Real W1 must have SWAGE (truss chord connections)");
}
